apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: weo7pz7o4-nodejs
  janus-idp.io/tekton: weo7pz7o4-nodejs
  backstage.io/kubernetes-id: weo7pz7o4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: weo7pz7o4-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
